name: GKE CI-CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-5706452a-7c84-467b-abb
  REGION: us-central1
  REPOSITORY: k8s-images

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display information
        run: |
          echo "GitHub Actions started"
          echo "Commit: $GITHUB_SHA"
          echo "Repository: $GITHUB_REPOSITORY"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/600309486002/locations/global/workloadIdentityPools/github-pool2/providers/github-provider"
          service_account: "github-gke-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure GCP project
        run: |
          gcloud config set project $PROJECT_ID

      - name: Verify Google Cloud authentication
        run: |
          echo "Project: $PROJECT_ID"
          gcloud auth list
          gcloud config get-value project

      - name: List Artifact Registry repositories
        run: |
          gcloud artifacts repositories list \
            --location=$REGION

      - name: Docker version
        run: |
          docker --version

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker \
            "${REGION}-docker.pkg.dev" \
            --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Display pushed image
        run: |
          echo "Image pushed successfully:"
          echo "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}"
